# Generated by Django 3.2.6 on 2021-09-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='palmares',
            fields=[
                ('idpiloto', models.AutoField(primary_key=True, serialize=False)),
                ('titulos', models.PositiveIntegerField(max_length=3)),
                ('victoias', models.PositiveIntegerField(max_length=4)),
                ('poles', models.PositiveIntegerField(max_length=4)),
                ('abandonos', models.PositiveIntegerField(max_length=4)),
                ('vueltasr', models.PositiveIntegerField(max_length=3)),
                ('inicio', models.DateTimeField()),
                ('retiro', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.piloto')),
            ],
            options={
                'verbose_name': 'palmares',
                'verbose_name_plural': 'palmares',
            },
        ),
    ]
