# Generated by Django 3.2.6 on 2021-09-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_palmares'),
    ]

    operations = [
        migrations.CreateModel(
            name='pole',
            fields=[
                ('ano', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('posicicion', models.PositiveIntegerField(max_length=3)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='stats')),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.piloto')),
            ],
            options={
                'verbose_name': 'pole',
                'verbose_name_plural': 'poles',
            },
        ),
    ]
