# Generated by Django 3.2.6 on 2021-09-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_pole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palmares',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pole',
            name='id',
        ),
        migrations.DeleteModel(
            name='carrera',
        ),
        migrations.DeleteModel(
            name='palmares',
        ),
        migrations.DeleteModel(
            name='piloto',
        ),
        migrations.DeleteModel(
            name='pole',
        ),
    ]
