# Generated by Django 3.2.6 on 2021-09-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0005_auto_20210907_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='piloto',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='stats')),
                ('created', models.DateTimeField(auto_now=True)),
                ('nacimiento', models.DateTimeField()),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'piloto',
                'verbose_name_plural': 'pilotos',
            },
        ),
    ]
