# Generated by Django 3.2.6 on 2021-09-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_pole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['-posicicion'], 'verbose_name': 'carrera', 'verbose_name_plural': 'carreras'},
        ),
    ]
