# Generated by Django 3.2.6 on 2021-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_carrera_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrera',
            name='ano',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
