# Generated by Django 3.2.6 on 2021-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20210909_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='stats'),
        ),
    ]
