# Generated by Django 3.2.6 on 2021-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_carrera_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='posicicion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='abandonos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='poles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='titulos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='victoias',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='vueltasr',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pole',
            name='posicicion',
            field=models.PositiveIntegerField(),
        ),
    ]
